export const upperFooterData = [
  {
    title: "Company",
    page: [
      { to: "About", link: "/aboutus" },
      { to: "Contact us", link: "/contactus" },
      { to: "Blog", link: "/#" },
      { to: "Career", link: "/career" },
      { to: "Media", link: "/media" },
      { to: "Faq", link: "/faq" },
      { to: "Lubricants", link: "/lubricants" },
      { to: "Review", link: "/reviews" },
      { to: "Terms & Condition", link: "/termsncondition" },
      { to: "Privacy Policy", link: "/privacypolicy" },
    ],
  },
  {
    title: "Top Pages",
    page: [
      { to: "Car Service In Gurgaon", link: "/car-service" },
      { to: "Car Service In Mumbai", link: "/car-service" },
      { to: "Car Service In Delhi", link: "/car-service" },
      { to: "Car Service In Ghaziabad", link: "/car-service" },
      { to: "Car Service In Pune", link: "/car-service" },
      { to: "Car Service In Bengaluru", link: "/car-service" },
      { to: "Car Service In Ahmedabad", link: "/car-service" },
      { to: "Car Service In Chandigarh", link: "/car-service" },
      { to: "Car Service In Faridabad", link: "/car-service" },
    ],
  },
  {
    title: "Popular Brands",
    page: [
      { to: "Maruti Suzuki", link: "/services" },
      { to: "Tata", link: "/services" },
      { to: "Honda", link: "/services" },
      { to: "Toyota", link: "/services" },
      { to: "Hyundai", link: "/services" },
      { to: "Kia", link: "/services" },
      { to: "MG", link: "/services" },
      { to: "Audi", link: "/services" },
      { to: "Mahindra", link: "/services" },
    ],
  },
  {
    title: "Services Near By",
    page: [
      { to: "Car Workshop Near Me", link: "/#" },
      { to: "Car Garage Near Me", link: "/#" },
      { to: "Car Mechanic Near Me", link: "/#" },
      { to: "Car Wash Near Me", link: "/#" },
      { to: "Car AC Repair Near Me", link: "/#" },
      { to: "Car Repair Near Me", link: "/#" },
      { to: "Car Service Near Me", link: "/#" },
      { to: "Car Scrapping", link: "/car-scrapping" },
      { to: "Partner Workshop", link: "/workshop-booking" },
    ],
  },
];
