export const upperFooterData = [
  {
    title: "Company",
    page: [
      { to: "About", link: "#" },
      { to: "Contact us", link: "#" },
      { to: "Blog", link: "#" },
      { to: "Career", link: "#" },
      { to: "Media", link: "/media" },
      { to: "Faq", link: "/faq" },
      { to: "Lubricants", link: "#" },
      { to: "Review", link: "/reviews" },
      { to: "Terms & Condition", link: "/termsncondition" },
      { to: "Privacy Policy", link: "/privacypolicy" },
    ],
  },
  {
    title: "Top Pages",
    page: [
      { to: "Car Service In Gurgaon", link: "#" },
      { to: "Car Service In Mumbai", link: "#" },
      { to: "Car Service In Delhi", link: "#" },
      { to: "Car Service In Ghaziabad", link: "#" },
      { to: "Car Service In Pune", link: "#" },
      { to: "Car Service In Bengaluru", link: "#" },
      { to: "Car Service In Ahmedabad", link: "#" },
      { to: "Car Service In Chandigarh", link: "#" },
      { to: "Car Service In Faridabad", link: "#" },
    ],
  },
  {
    title: "Popular Brands",
    page: [
      { to: "Maruti Suzuki", link: "#" },
      { to: "Tata", link: "#" },
      { to: "Honda", link: "#" },
      { to: "Toyota", link: "#" },
      { to: "Hyundai", link: "#" },
      { to: "Kia", link: "#" },
      { to: "MG", link: "#" },
      { to: "Audi", link: "#" },
      { to: "Mahindra", link: "#" },
    ],
  },
  {
    title: "Services Near By",
    page: [
      { to: "Car Workshop Near Me", link: "#" },
      { to: "Car Garage Near Me", link: "#" },
      { to: "Car Mechanic Near Me", link: "#" },
      { to: "Car Wash Near Me", link: "#" },
      { to: "Car AC Repair Near Me", link: "#" },
      { to: "Car Repair Near Me", link: "#" },
      { to: "Car Service Near Me", link: "#" },
      { to: "Car Scrapping", link: "#" },
      { to: "Partner Workshop", link: "#" },
    ],
  },
];
